### ISSUE TITLE
Cannot resize window causes some issue

### ISSUE THREAD

**Issue by pighair** [daidodo/diablo_edit#26] opened 2022-06-30 12:53 UTC
![image](https://user-images.githubusercontent.com/18534209/176681238-eaa20ef2-a345-4925-b9bb-5fd72a5ec32a.png)
![image](https://user-images.githubusercontent.com/18534209/176681560-4fa6c499-28f1-4454-bcc4-afa700471304.png)
![image](https://user-images.githubusercontent.com/18534209/176681603-0a00cbab-3562-4733-864a-891e4f9df67e.png)

I cannot access to some parts of screen because default window size is too small and I cannot resize.
I can access those parts by maximizing window but resizing would be much better.

Please fix to enable resizing.

**Comment by daidodo** [comment] 2022-07-04 10:23
Thanks for the feedback!

The issue is known but I may not have time to fix it. If you or anyone could help, that's be great!

**Comment by daidodo** [comment] 2022-12-10 20:16
Should be fixed in https://github.com/daidodo/diablo_edit/releases/tag/0.29.

**Closed** 2022-12-14 07:38 UTC
Labels: bug, duplicate, help wanted
