### ISSUE TITLE
view of the app is not correct

### ISSUE THREAD

**Issue by aacaai** [daidodo/diablo_edit#49] opened 2022-11-10 08:57 UTC
![image](https://user-images.githubusercontent.com/117637228/201044993-8df0aae8-df7a-41e6-97c5-133953dc68f9.png)

画面显示不正确  可以更新吗

**Comment by daidodo** [comment] 2022-11-10 20:18
Duplicate of https://github.com/daidodo/diablo_edit/issues/11

**Comment by daidodo** [comment] 2022-12-10 20:15
Should be fixed in https://github.com/daidodo/diablo_edit/releases/tag/0.29.

**Closed** 2022-12-14 07:38 UTC
Labels: bug, duplicate, help wanted
