### ISSUE TITLE
This barbarian char gives error message when opening

### ISSUE THREAD

**Issue by LordTreufeldt** [daidodo/diablo_edit#40] opened 2022-10-03 17:24 UTC
The editor is giving this error message ...

![Bug](https://user-images.githubusercontent.com/99281698/193640130-0637df2e-f782-4615-82c0-c50d70a6a405.jpg)

... when trying to open this barbarian save:
[Aquiles.zip](https://github.com/daidodo/diablo_edit/files/9699558/Aquiles.zip)

**Comment by daidodo** [comment] 2022-10-04 20:45
Thanks for the feedback!

Fixed in https://github.com/daidodo/diablo_edit/releases/tag/0.22.

The issue is the Token of Absolution in the stash. Seems D2R has changed its Simple flag (used to be 0, but 1 now).

**Closed** 2022-10-07 19:43 UTC
Labels: bug
