### ISSUE TITLE
Thanks for the editor, and a possible error report.

### ISSUE THREAD

**Issue by hubnameis0** [daidodo/diablo_edit#13] opened 2021-11-26 14:16 UTC
Thanks a lot.

Editing a Javelin. using this editor, 
- whenever a javelin is edited,  the game is frozen.
- in the editor, quantity of a javelin is now shown.

**Comment by daidodo** [comment] 2021-11-26 20:16
Thanks for the feedback!

Could you share more details or screenshots?
What do you mean by "the game is frozen"?

**Comment by hubnameis0** [comment] 2021-12-03 16:04
Sorry for late reply.
Frozen meant crash down.
Good day~

**Comment by hubnameis0** [comment] 2021-12-03 17:28
![Capture 20211204 022545](https://user-images.githubusercontent.com/95088978/144646441-36ef90c5-05db-417e-ae76-2623412402ef.png)

**Comment by daidodo** [comment] 2021-12-04 08:16
Thanks for the files and screenshot!

Just to confirm, you are in D2 Resurrected, right?

**Comment by daidodo** [comment] 2021-12-05 23:22
@hubnameis0, the issue has been fixed in [v0.8](https://github.com/daidodo/diablo_edit/releases/tag/0.8) release.

### Root Cause

#### Why can't the editor read *111.d2s* and *Cassia.d2s*?

It's because for simple items (e.g. *Jade Figurine* and *Key To The Cairn Stone*) there is an extra bit of padding in the end of the item. This is tested only in D2R.

#### Why does D2R crash when viewing items for *Cassia.d2s*?

It's because there are some *bug* items with too many properties. I guess D2R has a limit when showing the property pop-up window. I've removed them and tested the following file can play well.

[Cassia.zip](https://github.com/daidodo/diablo_edit/files/7656992/Cassia.zip)

Hope those can help you and tell me if you have more questions!

**Comment by hubnameis0** [comment] 2021-12-06 14:24
Very thanks for your kind effort!!!
Maybe I would rather edit not too much. :)

**Closed** 2021-12-08 09:11 UTC
Labels: bug
